apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devops
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: foyerdb
  MYSQL_USER: foyeruser
  MYSQL_PASSWORD: foyerpass
